### PR TITLE
fix rare alignment issue while rendering

### PR DESCRIPTION
**Pull request by david-vanderson**
When the ArrayList(u8) "temp_buffer" is resized, it can start on an address that is not aligned correctly for the type we are putting into it, which causes a panic when we call std.mem.bytesAsSlice()

To fix it, we allocate extra space (worst case needs @alignOf(T)-1 extra bytes), and offset the beginning.

### CODE REVIEW

**Comment by MasterQ32** [comment]
Oh, nice catch!

I think a better fix is to use `ArrayListAligned(u8, 16)` or something like that, which guarantees the alignment of the items slice

**Comment by MasterQ32** [comment]
I think you should be able to remove the alignCasts now, as the slice is 16-aligned now

**Comment by david-vanderson** [comment]
Thanks!  Still have to do the alignment for T2, because if @alignOf(T1) == 4, and @alignOf(T2) == 8, then the end of the T1s could be non-aligned for T2.

**Comment by david-vanderson** [comment]
Oh sorry misunderstood.  Give me a sec.

**Comment by david-vanderson** [comment]
Huh.  Apparently not - bytesAsSlice does not do the ```@alignCast``` for us:
```
dvanderson@librem14:~/gui$ zig build sdl-test
/home/dvanderson/gui/libs/tinyvg/src/lib/parsing.zig:241:20: error: expected type '[]libs.tinyvg.src.lib.tinyvg.Path.Node', found '[]align(1) libs.tinyvg.src.lib.tinyvg.Path.Node'
            return result;
                   ^~~~~~
/home/dvanderson/gui/libs/tinyvg/src/lib/parsing.zig:241:20: note: pointer alignment '1' cannot cast into pointer alignment '4'

```

**Comment by david-vanderson** [comment]
Even swapping ```self.temp_buffer.items``` for ```self.temp_buffer.allocatedSlice()``` doesn't let us drop the alignCasts.  I'd say keep them unless you have a better idea?

**Comment by MasterQ32** [comment]
I'll try fixing the problem on my end. Merging now, looks good so far

**Comment by david-vanderson** [comment]
Thank you!

**Comment by MasterQ32** [comment]
CI is green, alignCast eradicated as much as possible

**Comment by MasterQ32** [comment]
I've just seen your gui library for zig! Nice work! 

If you're on discord, feel free to ping me, i'd like to hear about your experiences with TinyVG :)

**Pull request merged**
